### ISSUE TITLE
container build failed

### ISSUE THREAD

**Issue by GershonA** [sc0Vu/ethdock#9]
`/home/ethdock# docker-compose up -d workspace testrpc`
.....

`ERROR: Service 'workspace' failed to build: The command '/bin/sh -c echo "deb http://ftp.us.debian.org/debian unstable m                                                      ain contrib non-free" >> /etc/apt/sources.list.d/unstable.list &&     apt-get -y update &&     apt-get install -y -t uns                                                      table gcc-5 libboost-dev' returned a non-zero code: 100`

**Comment by sc0Vu** [comment]
@GershonA The root error is unmet package dependencies when install gcc5, I couldn't fix it after tried multiple times. Right now I remove the `porosity` support and find another tool for `Decompiler and Security Analysis tool for Blockchain-based Ethereum Smart-Contracts`.

Feel free to send a pr if you find good tool!

Thanks
